#pragma once

#include <QtGlobal>

#if defined(QT3DSCENEEDITORPLUGIN_LIBRARY)
#  define QT3DSCENEEDITORPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QT3DSCENEEDITORPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif
